/*
 * Created on 2024-07-16 ( 17:05:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Address"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="address", schema="public" )
public class Address implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="text", nullable=false, length=100)
    private String     text ;

    @Column(name="county", nullable=false, length=50)
    private String     county ;

    @Column(name="state", nullable=false, length=50)
    private String     state ;

    @Column(name="zip_code", nullable=false)
    private Integer    zipCode ;

    @Column(name="is_verify")
    private Boolean    isVerify ;

    @Column(name="is_house")
    private Boolean    isHouse ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="address")
    private List<Store> listOfStore ; 

    @OneToMany(mappedBy="address")
    private List<Order> listOfOrder ; 


    /**
     * Constructor
     */
    public Address() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setText( String text ) {
        this.text = text ;
    }
    public String getText() {
        return this.text;
    }

    public void setCounty( String county ) {
        this.county = county ;
    }
    public String getCounty() {
        return this.county;
    }

    public void setState( String state ) {
        this.state = state ;
    }
    public String getState() {
        return this.state;
    }

    public void setZipCode( Integer zipCode ) {
        this.zipCode = zipCode ;
    }
    public Integer getZipCode() {
        return this.zipCode;
    }

    public void setIsVerify( Boolean isVerify ) {
        this.isVerify = isVerify ;
    }
    public Boolean getIsVerify() {
        return this.isVerify;
    }

    public void setIsHouse( Boolean isHouse ) {
        this.isHouse = isHouse ;
    }
    public Boolean getIsHouse() {
        return this.isHouse;
    }

    //--- GETTERS FOR LINKS
    public List<Store> getListOfStore() {
        return this.listOfStore;
    } 

    public List<Order> getListOfOrder() {
        return this.listOfOrder;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(text);
        sb.append("|");
        sb.append(county);
        sb.append("|");
        sb.append(state);
        sb.append("|");
        sb.append(zipCode);
        sb.append("|");
        sb.append(isVerify);
        sb.append("|");
        sb.append(isHouse);
        return sb.toString(); 
    } 

}
