/*
 * Created on 2024-07-21 ( 18:11:21 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Batch"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="batch", schema="public" )
public class Batch implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="cant_orders", nullable=false)
    private Integer    cantOrders ;

    @Temporal(TemporalType.DATE)
    @Column(name="date")
    private Date       date ;

    @Column(name="multi_store")
    private Boolean    multiStore ;

    @Column(name="shopper_id", nullable=false)
    private Integer    shopperId ;

    @Column(name="stores", length=250)
    private String     stores ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="shopper_id", referencedColumnName="id", insertable=false, updatable=false)
    private Shopper    shopper ; 

    @OneToMany(mappedBy="batch")
    private List<Image> listOfImage ; 


    /**
     * Constructor
     */
    public Batch() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setCantOrders( Integer cantOrders ) {
        this.cantOrders = cantOrders ;
    }
    public Integer getCantOrders() {
        return this.cantOrders;
    }

    public void setDate( Date date ) {
        this.date = date ;
    }
    public Date getDate() {
        return this.date;
    }

    public void setMultiStore( Boolean multiStore ) {
        this.multiStore = multiStore ;
    }
    public Boolean getMultiStore() {
        return this.multiStore;
    }

    public void setShopperId( Integer shopperId ) {
        this.shopperId = shopperId ;
    }
    public Integer getShopperId() {
        return this.shopperId;
    }

    public void setStores( String stores ) {
        this.stores = stores ;
    }
    public String getStores() {
        return this.stores;
    }

    //--- GETTERS FOR LINKS
    public Shopper getShopper() {
        return this.shopper;
    } 

    public List<Image> getListOfImage() {
        return this.listOfImage;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(cantOrders);
        sb.append("|");
        sb.append(date);
        sb.append("|");
        sb.append(multiStore);
        sb.append("|");
        sb.append(shopperId);
        sb.append("|");
        sb.append(stores);
        return sb.toString(); 
    } 

}
