/*
 * Created on 2024-07-21 ( 18:11:21 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.demo.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "Image"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="image", schema="public" )
public class Image implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="type", length=10)
    private String     type ;

    @Column(name="path", length=150)
    private String     path ;

    @Column(name="batch_id", nullable=false)
    private Integer    batchId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="batch_id", referencedColumnName="id", insertable=false, updatable=false)
    private Batch      batch ; 


    /**
     * Constructor
     */
    public Image() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setType( String type ) {
        this.type = type ;
    }
    public String getType() {
        return this.type;
    }

    public void setPath( String path ) {
        this.path = path ;
    }
    public String getPath() {
        return this.path;
    }

    public void setBatchId( Integer batchId ) {
        this.batchId = batchId ;
    }
    public Integer getBatchId() {
        return this.batchId;
    }

    //--- GETTERS FOR LINKS
    public Batch getBatch() {
        return this.batch;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(type);
        sb.append("|");
        sb.append(path);
        sb.append("|");
        sb.append(batchId);
        return sb.toString(); 
    } 

}
