/*
 * Created on 2024-07-21 ( 18:11:21 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * JPA entity class for "Order"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="order", schema="public" )
public class Order implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="total_items")
    private Integer    totalItems ;

    @Temporal(TemporalType.DATE)
    @Column(name="date")
    private Date       date ;

    @Column(name="is_gift", nullable=false)
    private Boolean    isGift ;

    @Column(name="note", length=200)
    private String     note ;

    @Column(name="tip")
    private Double     tip ;

    @Column(name="customer_id")
    private Integer    customerId ;

    @Column(name="store_id")
    private Integer    storeId ;

    @Column(name="batch_id")
    private Integer    batchId ;

    @Column(name="shopper_notes", length=250)
    private String     shopperNotes ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="due_date")
    private Date       dueDate ;

    @Column(name="number_order")
    private Integer    numberOrder ;

    @Column(name="address_id", nullable=false)
    private Integer    addressId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="store_id", referencedColumnName="id", insertable=false, updatable=false)
    private Store      store ; 

    @ManyToOne
    @JoinColumn(name="customer_id", referencedColumnName="id", insertable=false, updatable=false)
    private Customer   customer ; 

    @ManyToOne
    @JoinColumn(name="address_id", referencedColumnName="id", insertable=false, updatable=false)
    private Address    address ; 


    /**
     * Constructor
     */
    public Order() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setTotalItems( Integer totalItems ) {
        this.totalItems = totalItems ;
    }
    public Integer getTotalItems() {
        return this.totalItems;
    }

    public void setDate( Date date ) {
        this.date = date ;
    }
    public Date getDate() {
        return this.date;
    }

    public void setIsGift( Boolean isGift ) {
        this.isGift = isGift ;
    }
    public Boolean getIsGift() {
        return this.isGift;
    }

    public void setNote( String note ) {
        this.note = note ;
    }
    public String getNote() {
        return this.note;
    }

    public void setTip( Double tip ) {
        this.tip = tip ;
    }
    public Double getTip() {
        return this.tip;
    }

    public void setCustomerId( Integer customerId ) {
        this.customerId = customerId ;
    }
    public Integer getCustomerId() {
        return this.customerId;
    }

    public void setStoreId( Integer storeId ) {
        this.storeId = storeId ;
    }
    public Integer getStoreId() {
        return this.storeId;
    }

    public void setBatchId( Integer batchId ) {
        this.batchId = batchId ;
    }
    public Integer getBatchId() {
        return this.batchId;
    }

    public void setShopperNotes( String shopperNotes ) {
        this.shopperNotes = shopperNotes ;
    }
    public String getShopperNotes() {
        return this.shopperNotes;
    }

    public void setDueDate( Date dueDate ) {
        this.dueDate = dueDate ;
    }
    public Date getDueDate() {
        return this.dueDate;
    }

    public void setNumberOrder( Integer numberOrder ) {
        this.numberOrder = numberOrder ;
    }
    public Integer getNumberOrder() {
        return this.numberOrder;
    }

    public void setAddressId( Integer addressId ) {
        this.addressId = addressId ;
    }
    public Integer getAddressId() {
        return this.addressId;
    }

    //--- GETTERS FOR LINKS
    public Store getStore() {
        return this.store;
    } 

    public Customer getCustomer() {
        return this.customer;
    } 

    public Address getAddress() {
        return this.address;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(totalItems);
        sb.append("|");
        sb.append(date);
        sb.append("|");
        sb.append(isGift);
        sb.append("|");
        sb.append(note);
        sb.append("|");
        sb.append(tip);
        sb.append("|");
        sb.append(customerId);
        sb.append("|");
        sb.append(storeId);
        sb.append("|");
        sb.append(batchId);
        sb.append("|");
        sb.append(shopperNotes);
        sb.append("|");
        sb.append(dueDate);
        sb.append("|");
        sb.append(numberOrder);
        sb.append("|");
        sb.append(addressId);
        return sb.toString(); 
    } 

}
