/*
 * Created on 2024-07-21 ( 18:11:22 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.demo.entities;

import java.io.Serializable;
import javax.persistence.*;

/**
 * JPA entity class for "Prueba2"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="prueba2", schema="public" )
public class Prueba2 implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="cadena", length=20)
    private String     cadena ;

    @Column(name="p_id", nullable=false)
    private Integer    pId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="p_id", referencedColumnName="id", insertable=false, updatable=false)
    private Prueba     prueba ; 


    /**
     * Constructor
     */
    public Prueba2() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setCadena( String cadena ) {
        this.cadena = cadena ;
    }
    public String getCadena() {
        return this.cadena;
    }

    public void setPId( Integer pId ) {
        this.pId = pId ;
    }
    public Integer getPId() {
        return this.pId;
    }

    //--- GETTERS FOR LINKS
    public Prueba getPrueba() {
        return this.prueba;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(cadena);
        sb.append("|");
        sb.append(pId);
        return sb.toString(); 
    } 

}
