/*
 * Created on 2024-07-21 ( 18:11:21 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Prueba"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="prueba", schema="public" )
public class Prueba implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="cadena", length=100)
    private String     cadena ;

    @Column(name="numero")
    private Integer    numero ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="prueba")
    private List<Prueba2> listOfPrueba2 ; 


    /**
     * Constructor
     */
    public Prueba() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setCadena( String cadena ) {
        this.cadena = cadena ;
    }
    public String getCadena() {
        return this.cadena;
    }

    public void setNumero( Integer numero ) {
        this.numero = numero ;
    }
    public Integer getNumero() {
        return this.numero;
    }

    //--- GETTERS FOR LINKS
    public List<Prueba2> getListOfPrueba2() {
        return this.listOfPrueba2;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(cadena);
        sb.append("|");
        sb.append(numero);
        return sb.toString(); 
    } 

}
