/*
 * Created on 2024-07-21 ( 18:11:22 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package org.demo.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Store"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="store", schema="public" )
public class Store implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="name", nullable=false, length=100)
    private String     name ;

    @Column(name="code", length=10)
    private String     code ;

    @Column(name="address_id", nullable=false)
    private Integer    addressId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="address_id", referencedColumnName="id", insertable=false, updatable=false)
    private Address    address ; 

    @OneToMany(mappedBy="store")
    private List<Order> listOfOrder ; 


    /**
     * Constructor
     */
    public Store() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setCode( String code ) {
        this.code = code ;
    }
    public String getCode() {
        return this.code;
    }

    public void setAddressId( Integer addressId ) {
        this.addressId = addressId ;
    }
    public Integer getAddressId() {
        return this.addressId;
    }

    //--- GETTERS FOR LINKS
    public Address getAddress() {
        return this.address;
    } 

    public List<Order> getListOfOrder() {
        return this.listOfOrder;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(code);
        sb.append("|");
        sb.append(addressId);
        return sb.toString(); 
    } 

}
