package com.batch.history.models;// Generated Jun 30, 2024, 9:57:25 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", schema = "public")
public class Address implements java.io.Serializable {

	private int id;
	private String text;
	private String county;
	private String state;
	private int zipCode;
	private Boolean isVerify;
	private Boolean isHouse;
	private Set customers = new HashSet(0);
	private Set stores = new HashSet(0);

	public Address() {
	}

	public Address(int id, String text, String county, String state, int zipCode) {
		this.id = id;
		this.text = text;
		this.county = county;
		this.state = state;
		this.zipCode = zipCode;
	}

	public Address(int id, String text, String county, String state, int zipCode, Boolean isVerify, Boolean isHouse,
			Set customers, Set stores) {
		this.id = id;
		this.text = text;
		this.county = county;
		this.state = state;
		this.zipCode = zipCode;
		this.isVerify = isVerify;
		this.isHouse = isHouse;
		this.customers = customers;
		this.stores = stores;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "text", nullable = false, length = 100)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "county", nullable = false, length = 50)
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "state", nullable = false, length = 50)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "zip_code", nullable = false)
	public int getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(int zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "is_verify")
	public Boolean getIsVerify() {
		return this.isVerify;
	}

	public void setIsVerify(Boolean isVerify) {
		this.isVerify = isVerify;
	}

	@Column(name = "is_house")
	public Boolean getIsHouse() {
		return this.isHouse;
	}

	public void setIsHouse(Boolean isHouse) {
		this.isHouse = isHouse;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	public Set getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set customers) {
		this.customers = customers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	public Set getStores() {
		return this.stores;
	}

	public void setStores(Set stores) {
		this.stores = stores;
	}

}
