package com.batch.history.models;
// Generated Jun 30, 2024, 9:57:25 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Batch generated by hbm2java
 */
@Entity
@Table(name = "batch", schema = "public")
public class Batch implements java.io.Serializable {

	private long id;
	private Shopper shopper;
	private int cantOrders;
	private Date date;
	private Boolean multiStore;
	private Set orders = new HashSet(0);

	public Batch() {
	}

	public Batch(long id, Shopper shopper, int cantOrders) {
		this.id = id;
		this.shopper = shopper;
		this.cantOrders = cantOrders;
	}

	public Batch(long id, Shopper shopper, int cantOrders, Date date, Boolean multiStore, Set orders) {
		this.id = id;
		this.shopper = shopper;
		this.cantOrders = cantOrders;
		this.date = date;
		this.multiStore = multiStore;
		this.orders = orders;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "shopper_id", nullable = false)
	public Shopper getShopper() {
		return this.shopper;
	}

	public void setShopper(Shopper shopper) {
		this.shopper = shopper;
	}

	@Column(name = "cant_orders", nullable = false)
	public int getCantOrders() {
		return this.cantOrders;
	}

	public void setCantOrders(int cantOrders) {
		this.cantOrders = cantOrders;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 13)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "multi_store")
	public Boolean getMultiStore() {
		return this.multiStore;
	}

	public void setMultiStore(Boolean multiStore) {
		this.multiStore = multiStore;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "batch")
	public Set getOrders() {
		return this.orders;
	}

	public void setOrders(Set orders) {
		this.orders = orders;
	}

}