package com.batch.history.models;
// Generated Jun 30, 2024, 9:57:25 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", schema = "public")
public class Customer implements java.io.Serializable {

	private long id;
	private Address address;
	private String name;
	private Integer cantOrder;
	private Boolean isGoodTipper;
	private Boolean isSuspicious;
	private Set orders = new HashSet(0);

	public Customer() {
	}

	public Customer(long id, Address address, String name) {
		this.id = id;
		this.address = address;
		this.name = name;
	}

	public Customer(long id, Address address, String name, Integer cantOrder, Boolean isGoodTipper,
			Boolean isSuspicious, Set orders) {
		this.id = id;
		this.address = address;
		this.name = name;
		this.cantOrder = cantOrder;
		this.isGoodTipper = isGoodTipper;
		this.isSuspicious = isSuspicious;
		this.orders = orders;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_id", nullable = false)
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "cant_order")
	public Integer getCantOrder() {
		return this.cantOrder;
	}

	public void setCantOrder(Integer cantOrder) {
		this.cantOrder = cantOrder;
	}

	@Column(name = "is_good_tipper")
	public Boolean getIsGoodTipper() {
		return this.isGoodTipper;
	}

	public void setIsGoodTipper(Boolean isGoodTipper) {
		this.isGoodTipper = isGoodTipper;
	}

	@Column(name = "is_suspicious")
	public Boolean getIsSuspicious() {
		return this.isSuspicious;
	}

	public void setIsSuspicious(Boolean isSuspicious) {
		this.isSuspicious = isSuspicious;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set getOrders() {
		return this.orders;
	}

	public void setOrders(Set orders) {
		this.orders = orders;
	}

}