package com.batch.history.models;
// Generated Jun 30, 2024, 9:57:25 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", schema = "public")
public class Order implements java.io.Serializable {

	private long id;
	private Batch batch;
	private Customer customer;
	private Store store;
	private Integer totalItems;
	private Date dueDate;
	private boolean isGift;
	private String note;
	private Double tip;
	private String shopperNotes;
	private Date timePoped;
	private Set images = new HashSet(0);

	public Order() {
	}

	public Order(long id, boolean isGift) {
		this.id = id;
		this.isGift = isGift;
	}

	public Order(long id, Batch batch, Customer customer, Store store, Integer totalItems, Date dueDate, boolean isGift,
			String note, Double tip, String shopperNotes, Date timePoped, Set images) {
		this.id = id;
		this.batch = batch;
		this.customer = customer;
		this.store = store;
		this.totalItems = totalItems;
		this.dueDate = dueDate;
		this.isGift = isGift;
		this.note = note;
		this.tip = tip;
		this.shopperNotes = shopperNotes;
		this.timePoped = timePoped;
		this.images = images;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "batch_id")
	public Batch getBatch() {
		return this.batch;
	}

	public void setBatch(Batch batch) {
		this.batch = batch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "store_id")
	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	@Column(name = "total_items")
	public Integer getTotalItems() {
		return this.totalItems;
	}

	public void setTotalItems(Integer totalItems) {
		this.totalItems = totalItems;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "due_date", length = 35)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Column(name = "is_gift", nullable = false)
	public boolean isIsGift() {
		return this.isGift;
	}

	public void setIsGift(boolean isGift) {
		this.isGift = isGift;
	}

	@Column(name = "note", length = 200)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "tip", precision = 17, scale = 17)
	public Double getTip() {
		return this.tip;
	}

	public void setTip(Double tip) {
		this.tip = tip;
	}

	@Column(name = "shopper_notes", length = 250)
	public String getShopperNotes() {
		return this.shopperNotes;
	}

	public void setShopperNotes(String shopperNotes) {
		this.shopperNotes = shopperNotes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_poped", length = 35)
	public Date getTimePoped() {
		return this.timePoped;
	}

	public void setTimePoped(Date timePoped) {
		this.timePoped = timePoped;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	public Set getImages() {
		return this.images;
	}

	public void setImages(Set images) {
		this.images = images;
	}

}