package com.app.batch.model;

/*
 * Created on 2024-07-15 ( 21:49:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * JPA entity class for "Batch"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Entity
@Table(name="batch", schema="public" )
public class Batch implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="cant_orders", nullable=false)
    private Integer    cantOrders ;

    @Temporal(TemporalType.DATE)
    @Column(name="date")
    private Date       date ;

    @Column(name="multi_store")
    private Boolean    multiStore ;

    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JsonBackReference
    @JoinColumn(name="shopper_id", referencedColumnName="id", insertable=false, updatable=false)
    private Shopper    shopper ; 


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="batch")
    @JsonManagedReference
    private List<Order> listOfOrder ; 

    public Batch() {}

    
    public Batch(Long id, Integer cantOrders, Date date, Boolean multiStore, Shopper shopper,
			List<Order> listOfOrder) {
		
		this.id = id;
		this.cantOrders = cantOrders;
		this.date = date;
		this.multiStore = multiStore;
		this.shopper = shopper;
		this.listOfOrder = listOfOrder;
	}

	//--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(cantOrders);
        sb.append("|");
        sb.append(date);
        sb.append("|");
        sb.append(multiStore);
        sb.append("|");
        return sb.toString(); 
    }


	public Long getId() {
		return id;
	}


	public void setId(Long id) {
		this.id = id;
	}


	public Integer getCantOrders() {
		return cantOrders;
	}


	public void setCantOrders(Integer cantOrders) {
		this.cantOrders = cantOrders;
	}


	public Date getDate() {
		return date;
	}


	public void setDate(Date date) {
		this.date = date;
	}


	public Boolean getMultiStore() {
		return multiStore;
	}


	public void setMultiStore(Boolean multiStore) {
		this.multiStore = multiStore;
	}


	public Shopper getShopper() {
		return shopper;
	}


	public void setShopper(Shopper shopper) {
		this.shopper = shopper;
	}


	public List<Order> getListOfOrder() {
		return listOfOrder;
	}


	public void setListOfOrder(List<Order> listOfOrder) {
		this.listOfOrder = listOfOrder;
	} 

	
}

