package com.app.batch.model;

/*
 * Created on 2024-07-15 ( 21:49:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

import java.io.Serializable;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonManagedReference;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * JPA entity class for "Shopper"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Entity
@Table(name="shopper", schema="public" )
public class Shopper implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="code", nullable=false, length=10)
    private String     code ;

    @Column(name="name", nullable=false, length=80)
    private String     name ;

    @Column(name="phone_number")
    private Long       phoneNumber ;

    @Column(name="sex")
    private Boolean    sex ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="shopper")
    @JsonManagedReference
    private List<Batch> listOfBatch ; 
    
    
    /**
     * Constructor
     */
    public Shopper() {
    }
    

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(code);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(phoneNumber);
        sb.append("|");
        sb.append(sex);
        return sb.toString(); 
    }


	public Shopper(Long id, String code, String name, Long phoneNumber, Boolean sex) {
		
		this.id = id;
		this.code = code;
		this.name = name;
		this.phoneNumber = phoneNumber;
		this.sex = sex;
	}


	public Long getId() {
		return id;
	}


	public void setId(Long id) {
		this.id = id;
	}


	public String getCode() {
		return code;
	}


	public void setCode(String code) {
		this.code = code;
	}


	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}


	public Long getPhoneNumber() {
		return phoneNumber;
	}


	public void setPhoneNumber(Long phoneNumber) {
		this.phoneNumber = phoneNumber;
	}


	public Boolean getSex() {
		return sex;
	}


	public void setSex(Boolean sex) {
		this.sex = sex;
	}


	public List<Batch> getListOfBatch() {
		return listOfBatch;
	}


	public void setListOfBatch(List<Batch> listOfBatch) {
		this.listOfBatch = listOfBatch;
	} 

}
