package com.app.batch.model;

/*
 * Created on 2024-07-15 ( 21:49:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonManagedReference;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * JPA entity class for "Customer"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Entity
@Table(name="customer", schema="public" )
public class Customer implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="name", nullable=false, length=100)
    private String     name ;

    @Column(name="is_good_tipper")
    private Boolean    isGoodTipper ;

    @Column(name="is_suspicious")
    private Boolean    isSuspicious ;

    @Temporal(TemporalType.DATE)
    @Column(name="register_date")
    private Date       registerDate ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="customer")
    @JsonManagedReference
    private List<Order> listOfOrder ; 

    public Customer(){}

    public Customer(Long id, String name, Boolean isGoodTipper, Boolean isSuspicious, Date registerDate,
			List<Order> listOfOrder) {
		
		this.id = id;
		this.name = name;
		this.isGoodTipper = isGoodTipper;
		this.isSuspicious = isSuspicious;
		this.registerDate = registerDate;
		this.listOfOrder = listOfOrder;
	}




	//--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(isGoodTipper);
        sb.append("|");
        sb.append(isSuspicious);
        sb.append("|");
        sb.append(registerDate);
        return sb.toString(); 
    }

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getIsGoodTipper() {
		return isGoodTipper;
	}

	public void setIsGoodTipper(Boolean isGoodTipper) {
		this.isGoodTipper = isGoodTipper;
	}

	public Boolean getIsSuspicious() {
		return isSuspicious;
	}

	public void setIsSuspicious(Boolean isSuspicious) {
		this.isSuspicious = isSuspicious;
	}

	public Date getRegisterDate() {
		return registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	public List<Order> getListOfOrder() {
		return listOfOrder;
	}

	public void setListOfOrder(List<Order> listOfOrder) {
		this.listOfOrder = listOfOrder;
	} 

}

