package com.app.batch.model;

/*
 * Created on 2024-07-15 ( 21:49:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonBackReference;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * JPA entity class for "Image"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Entity
@Table(name="image", schema="public" )
public class Image implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="type", length=10)
    private String     type ;

    @Column(name="path", length=150)
    private String     path ;

    @Column(name="order_id", nullable=false)
    private Long    orderId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JsonBackReference
    @JoinColumn(name="order_id", referencedColumnName="id", insertable=false, updatable=false)
    private Order      order ; 

    public Image() {}
    
    public Image(Long id, String type, String path, Long orderId, Order order) {
		
		this.id = id;
		this.type = type;
		this.path = path;
		this.orderId = orderId;
		this.order = order;
	}


	//--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(type);
        sb.append("|");
        sb.append(path);
        sb.append("|");
        sb.append(orderId);
        return sb.toString(); 
    }

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getPath() {
		return path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Long getOrderId() {
		return orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	public Order getOrder() {
		return order;
	}

	public void setOrder(Order order) {
		this.order = order;
	} 

}

