package com.app.batch.model;

/*
 * Created on 2024-07-15 ( 21:49:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

import java.io.Serializable;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * JPA entity class for "Store"
 *
 * @author Telosys
 *
 */
@Getter
@Setter
@Entity
@Table(name="store", schema="public" )
public class Store implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="name", nullable=false, length=100)
    private String     name ;

    @Column(name="code", length=10)
    private String     code ;

    @Column(name="address_id", nullable=false)
    private Long    addressId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="address_id", referencedColumnName="id", insertable=false, updatable=false)
    @JsonBackReference
    private Address    address ; 

    @OneToMany(mappedBy="store")
    @JsonManagedReference
    private List<Order> listOfOrder ; 

    public Store() {}

	public Store(Long id, String name, String code, Long addressId, Address address, List<Order> listOfOrder) {
		
		this.id = id;
		this.name = name;
		this.code = code;
		this.addressId = addressId;
		this.address = address;
		this.listOfOrder = listOfOrder;
	}


	//--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(code);
        sb.append("|");
        sb.append(addressId);
        return sb.toString(); 
    }

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Long getAddressId() {
		return addressId;
	}

	public void setAddressId(Long addressId) {
		this.addressId = addressId;
	}

	public Address getAddress() {
		return address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public List<Order> getListOfOrder() {
		return listOfOrder;
	}

	public void setListOfOrder(List<Order> listOfOrder) {
		this.listOfOrder = listOfOrder;
	} 

	
}

