package com.app.batch.model;
// Generated Jul 15, 2024, 6:02:34 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", schema = "public")
public class Customer implements java.io.Serializable {

	private long id;
	private String name;
	private Boolean isGoodTipper;
	private Boolean isSuspicious;
	private Date registerDate;
	private Set<Order> orders = new HashSet<Order>(0);

	public Customer() {
	}

	public Customer(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public Customer(long id, String name, Boolean isGoodTipper, Boolean isSuspicious, Date registerDate,
			Set<Order> orders) {
		this.id = id;
		this.name = name;
		this.isGoodTipper = isGoodTipper;
		this.isSuspicious = isSuspicious;
		this.registerDate = registerDate;
		this.orders = orders;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "is_good_tipper")
	public Boolean getIsGoodTipper() {
		return this.isGoodTipper;
	}

	public void setIsGoodTipper(Boolean isGoodTipper) {
		this.isGoodTipper = isGoodTipper;
	}

	@Column(name = "is_suspicious")
	public Boolean getIsSuspicious() {
		return this.isSuspicious;
	}

	public void setIsSuspicious(Boolean isSuspicious) {
		this.isSuspicious = isSuspicious;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "register_date", length = 13)
	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
