package com.app.batch.model;
// Generated Jul 15, 2024, 6:02:34 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Prueba generated by hbm2java
 */
@Entity
@Table(name = "prueba", schema = "public")
public class Prueba implements java.io.Serializable {

	private int id;
	private String cadena;
	private Integer numero;
	private Set<Prueba2> prueba2s = new HashSet<Prueba2>(0);

	public Prueba() {
	}

	public Prueba(int id) {
		this.id = id;
	}

	public Prueba(int id, String cadena, Integer numero, Set<Prueba2> prueba2s) {
		this.id = id;
		this.cadena = cadena;
		this.numero = numero;
		this.prueba2s = prueba2s;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "cadena", length = 100)
	public String getCadena() {
		return this.cadena;
	}

	public void setCadena(String cadena) {
		this.cadena = cadena;
	}

	@Column(name = "numero")
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prueba")
	public Set<Prueba2> getPrueba2s() {
		return this.prueba2s;
	}

	public void setPrueba2s(Set<Prueba2> prueba2s) {
		this.prueba2s = prueba2s;
	}

}
