package com.app.batch.model;
// Generated Jul 15, 2024, 6:02:34 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Prueba2 generated by hbm2java
 */
@Entity
@Table(name = "prueba2", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "p_id"))
public class Prueba2 implements java.io.Serializable {

	private long id;
	private Prueba prueba;
	private String cadena;

	public Prueba2() {
	}

	public Prueba2(long id, Prueba prueba) {
		this.id = id;
		this.prueba = prueba;
	}

	public Prueba2(long id, Prueba prueba, String cadena) {
		this.id = id;
		this.prueba = prueba;
		this.cadena = cadena;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "p_id", unique = true, nullable = false)
	public Prueba getPrueba() {
		return this.prueba;
	}

	public void setPrueba(Prueba prueba) {
		this.prueba = prueba;
	}

	@Column(name = "cadena", length = 20)
	public String getCadena() {
		return this.cadena;
	}

	public void setCadena(String cadena) {
		this.cadena = cadena;
	}

}
