package com.app.batch.model;
// Generated Jul 15, 2024, 6:02:34 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Shopper generated by hbm2java
 */
@Entity
@Table(name = "shopper", schema = "public")
public class Shopper implements java.io.Serializable {

	private int id;
	private String code;
	private String name;
	private Long phoneNumber;
	private Boolean sex;
	private Set<Batch> batches = new HashSet<Batch>(0);

	public Shopper() {
	}

	public Shopper(int id, String code, String name) {
		this.id = id;
		this.code = code;
		this.name = name;
	}

	public Shopper(int id, String code, String name, Long phoneNumber, Boolean sex, Set<Batch> batches) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.phoneNumber = phoneNumber;
		this.sex = sex;
		this.batches = batches;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "code", nullable = false, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 80)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "phone_number")
	public Long getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(Long phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "sex")
	public Boolean getSex() {
		return this.sex;
	}

	public void setSex(Boolean sex) {
		this.sex = sex;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopper")
	public Set<Batch> getBatches() {
		return this.batches;
	}

	public void setBatches(Set<Batch> batches) {
		this.batches = batches;
	}

}
